# Generated by Django 6.0 on 2025-12-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrada',
            name='membresia_activa',
            field=models.BooleanField(default=False),
        ),
    ]
