# Generated by Django 6.0 on 2025-12-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_registroentrada_membresia_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='matricula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
